// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFhJcp3ktTZ6kgiSDfQt57TeuSjJAdcnc',
    appId: '1:29314710923:web:cb850cdbc36b74dce5c38e',
    messagingSenderId: '29314710923',
    projectId: 'safe-route-f2693',
    authDomain: 'safe-route-f2693.firebaseapp.com',
    storageBucket: 'safe-route-f2693.appspot.com',
    measurementId: 'G-KSKS880XZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6ApxvooWnuAMIH8c2ARhsfe7_IsrDbh4',
    appId: '1:29314710923:android:56bcce4fddde6a61e5c38e',
    messagingSenderId: '29314710923',
    projectId: 'safe-route-f2693',
    storageBucket: 'safe-route-f2693.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWUaxvlV-4pnzwiNKsuRiBsP0YctMaBAs',
    appId: '1:29314710923:ios:b362b901e70c81b0e5c38e',
    messagingSenderId: '29314710923',
    projectId: 'safe-route-f2693',
    storageBucket: 'safe-route-f2693.appspot.com',
    iosBundleId: 'com.example.safeRoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWUaxvlV-4pnzwiNKsuRiBsP0YctMaBAs',
    appId: '1:29314710923:ios:b362b901e70c81b0e5c38e',
    messagingSenderId: '29314710923',
    projectId: 'safe-route-f2693',
    storageBucket: 'safe-route-f2693.appspot.com',
    iosBundleId: 'com.example.safeRoute',
  );
}
